version: '3'

services:
  app:
    build:
      context: .
    ports:
      -'80:80'
    volumes:
      -.app:/code/app
    depends_on:
      - db

  db:
    image: portgres:14
    ports:
      - "5435:5432"
    volumes:
      - portgres_data:/var/lib/postgresql/data
    
volumes:
  portgres_data: